import React from 'react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-zinc-950 w-full">
      <div className="text-zinc-100 p-8 md:p-16 max-w-4xl mx-auto font-sans leading-relaxed">
        <h1 className="text-3xl font-bold mb-8 font-display">FaultLine Terms of Service</h1>
      
      <div className="space-y-8 text-zinc-300">
        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-white">1. Acceptance of Terms</h2>
          <p>Welcome to FaultLine. By accessing or using our application, you agree to comply with and be bound by these Terms of Service. If you do not agree with these Terms, you must not access or use the application.</p>
          <p>FaultLine provides a risk decision system that enables users to analyze transcripts, evaluate business risks, and build a prioritized portfolio based on the information provided.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-white">2. Acceptable Use</h2>
          <p>You agree to use FaultLine only for lawful purposes and in a manner that does not disrupt, damage, overload, or impair the application or its services.</p>
          <p>You are solely responsible for all content, transcripts, financial data, business information, and other materials that you upload, submit, or enter into the application.</p>
          <p>You agree not to misuse the application, attempt unauthorized access, interfere with system security, or use FaultLine for any fraudulent, harmful, or unlawful activity.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-white">3. User Responsibilities and Conduct</h2>
          <p>You are responsible for ensuring that any information uploaded to FaultLine is accurate, lawful, and authorized for use.</p>
          <p>You must not upload sensitive Personally Identifiable Information, confidential business data, or regulated information into the transcript analyzer unless you have proper authorization from your organization or the relevant data owner.</p>
          <p>You are also responsible for maintaining the security and confidentiality of your connected Google account and any related login credentials. FaultLine is not responsible for unauthorized access resulting from your failure to secure your account.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-white">4. Service Modifications and Limitations</h2>
          <p>FaultLine reserves the right to modify, suspend, restrict, or discontinue the application or any part of its services at any time, with or without prior notice.</p>
          <p>The analyses, risk calibrations, scores, rankings, and recommendations generated by FaultLine are predictive and decision-support tools. They are provided for informational purposes only and should not be treated as financial, legal, investment, or professional advice.</p>
          <p>Users should not rely on FaultLine as the sole basis for making critical financial, operational, investment, or business decisions. Final decisions remain the responsibility of the user or their organization.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-white">5. Limitation of Liability</h2>
          <p>FaultLine does not guarantee the accuracy, completeness, reliability, or suitability of any analysis, prediction, recommendation, or output generated by the application.</p>
          <p>To the maximum extent permitted by law, FaultLine shall not be liable for any direct, indirect, incidental, consequential, or financial losses arising from your use of the application or reliance on its outputs.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-white">6. Changes to These Terms</h2>
          <p>We may update these Terms of Service from time to time. Continued use of FaultLine after any changes means that you accept the revised Terms.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-white">7. Contact</h2>
          <p>For questions about these Terms of Service, please contact the FaultLine team <a href="mailto:faultlinesupport@gmail.com" className="text-blue-400 hover:underline">faultlinesupport@gmail.com</a>.</p>
        </section>
        
        <div className="pt-8 border-t border-zinc-800">
          <a href="#" className="inline-block text-sm bg-zinc-900 border border-zinc-800 px-4 py-2 rounded hover:bg-zinc-800 transition-colors">
            Back to App
          </a>
        </div>
      </div>
      </div>
    </div>
  );
}
